Repository mju-likelion/hackathon-team3-server, pull requests merged in 2023-08, with the labels that each got.

#5 Feature/#4 join login 로그인, 회원가입 기능 구현
  package.json
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/dto/join.dto.ts
  src/auth/dto/login.dto.ts
  src/config/authConfig.ts
  src/main.ts
Labels: enhancement

#11 Feature/#10 jwt 추가 작업
  package.json
  src/auth/auth-user.decorator.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/jwt/jwt.guard.ts
  src/auth/jwt/jwt.payload.ts
  src/auth/jwt/jwt.strategy.ts
  test/app.e2e-spec.ts
  yarn.lock
Labels: enhancement

#13 Feature/#6 user domain 작업
  package.json
  src/auth/auth.service.ts
  src/common/dtos/Response.dto.ts
  src/users/dtos/delete-account.dto.ts
  src/users/dtos/modify-password.dto.ts
  src/users/dtos/profile.dto.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.ts
  yarn.lock
Labels: documentation, enhancement

#16 Feat/#14 learning domain 작업
  src/learnings/dtos/chapters.dto.ts
  src/learnings/dtos/progress.dto.ts
  src/learnings/learnings.controller.ts
  src/learnings/learnings.module.ts
  src/learnings/learnings.service.ts
Labels: documentation, enhancement

#18 Feature/#9 openai 연동
  package.json
  src/apis/openai/config/openaiConfig.ts
  src/apis/openai/openai.module.ts
  src/apis/openai/openai.service.ts
  src/apis/openai/request/chatCompletionRequest.ts
  src/apis/openai/requestdto/request.dto.ts
  src/apis/openai/responsedto/response.dto.ts
  src/app.module.ts
  yarn.lock
Labels: enhancement, help wanted

#23 Feature/#22 getChapters method 반환값에 챕터별 완료 여부 추가
  src/learnings/learnings.service.ts
  yarn.lock
Labels: enhancement

#21 Feature/#20 refactor auth 모듈 dto 리팩터링
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/dtos/join-response.dto.ts
  src/auth/dtos/join.dto.ts
  src/auth/dtos/login-response.dto.ts
  src/auth/dtos/login.dto.ts
Labels: refactor

#26 Feature/#25 entity id컬럼 타입 수정
  src/chapters/entities/chapter.entity.ts
  src/learnings/entities/learning.entity.ts
  src/problems/entities/problem.entity.ts
  src/users/entities/users.entity.ts
Labels: bug

#28 Fix/#27 jwtpayload 수정
  src/auth/jwt/jwt.payload.ts
Labels: bug

#30 Feature/#24 예시 문제 제거
  src/problems/entities/problem.entity.ts
Labels: documentation, enhancement

#32 Feature/#31 챕터 정보 api 구현
  src/chapters/chapters.controller.ts
  src/chapters/chapters.module.ts
  src/chapters/chapters.service.ts
  src/chapters/dtos/chapter.dto.ts
  src/problems/entities/problem.entity.ts
  src/problems/utils/problem.util.ts
Labels: documentation, enhancement

#29 Feature/#19 문제 채점 구현
  src/apis/openai/dtos/optimize-string-response.dto.ts
  src/apis/openai/dtos/optimize-string.dto.ts
  src/apis/openai/dtos/score-problem-response.dto.ts
  src/apis/openai/dtos/score-problem.dto.ts
  src/apis/openai/openai.service.ts
  src/apis/openai/responsedto/response.dto.ts
  src/problems/dtos/submit-response.dto.ts
  src/problems/dtos/submit.dto.ts
  src/problems/problems.controller.ts
  src/problems/problems.module.ts
  src/problems/problems.service.ts
Labels: documentation, enhancement

#36 Feature/#34 answerOptions 컬럼 추가, 이에 따른 코드 변경
  src/chapters/chapters.service.ts
  src/problems/entities/problem.entity.ts
  src/problems/utils/problem.util.ts
Labels: enhancement, refactor

#39 Feature/#38 Entity property naming 수정, 이에 따른 코드 리팩터링
  src/chapters/chapters.service.ts
  src/chapters/entities/chapter.entity.ts
  src/learnings/learnings.service.ts
  src/users/entities/users.entity.ts
Labels: documentation, refactor

#44 !HOTFIX/#43 answerOptions validation 추가
  src/chapters/chapters.service.ts
  src/problems/problems.service.ts
Labels: bug

#46 !HOTFIX/#45 problem Create 시 발생하는 오류 메시지 수정
  src/problems/problems.service.ts
Labels: bug

#48 !HOTFIX/ #47 chapterService getChapter() 잘못된 조건문 수정
  src/chapters/chapters.service.ts
Labels: bug

#50 Feature/#49 openAI 요청 제한을 위한 Rate Limiting 구현
  package.json
  src/apis/openai/openai.module.ts
  src/apis/openai/openai.service.ts
  src/apis/openai/throttler-behind-proxy.guard.ts
  yarn.lock
Labels: enhancement

#51 Feature/#37 랜덤하게 3문제 반환 구현
  src/chapters/chapters.module.ts
  src/chapters/chapters.service.ts
  src/users/entities/users.entity.ts
Labels: enhancement

#56 Feature/#55 Rate Limiting이 전체 controller에 적용되는 현상 수정
  src/apis/openai/openai.module.ts
  src/apis/openai/openai.service.ts
  src/problems/problems.controller.ts
  src/problems/problems.module.ts
  src/problems/throttler-behind-proxy.guard.ts
Labels: bug

#58 Feature/#57 모든 예외를 적절한 예외로 수정
  src/auth/jwt/jwt.strategy.ts
  src/problems/problems.service.ts
Labels: documentation, refactor

#61 Feature/#60 jwt response, request 방식 전부 쿠키로 수정
  package.json
  src/auth/jwt/jwt.strategy.ts
  src/main.ts
  yarn.lock
Labels: enhancement

#63 Feature/#62 login response data에 nickName 추가
  src/auth/auth.service.ts
  src/auth/dtos/login-response.dto.ts
Labels: enhancement

#65 Feature/#64 Rate Limiting을 전역으로 설정
  src/app.module.ts
  src/common/throttler-behind-proxy.guard.ts
  src/problems/problems.controller.ts
  src/problems/problems.module.ts
Labels: enhancement

#70 !HOTFIX/#69 set-cookie 동작을 위한 추가 설정
  src/auth/auth.service.ts
  src/auth/jwt/jwt.strategy.ts
  src/main.ts
Labels: bug

#71 Feature/#59 진도율 로직 수정 및 api 수정
  src/learnings/dtos/chapters.dto.ts
  src/learnings/learnings.service.ts
Labels: documentation, enhancement

#76 !Hotfix/#76 chapter crud api에 order 반영
  src/chapters/chapters.service.ts
  src/chapters/dtos/crud/create/create.dto.ts
  src/chapters/dtos/crud/update/update.dto.ts
Labels: bug

#77 Feature/#74 채점 로직 수정
  src/problems/dtos/submit-response.dto.ts
  src/problems/dtos/submit.dto.ts
  src/problems/problems.service.ts
Labels: enhancement

#82 Feature/#81 openAI 질문 방식 수정
  src/apis/openai/openai.service.ts
Labels: bug, enhancement

#80 Feature/#78 chapter 조회 시 문제 완료 여부와 관계없이 반환하도록 수정
  src/chapters/chapters.service.ts
Labels: enhancement

#83 Feature/#74 채점 로직 수정
  src/problems/problems.service.ts
Labels: bug, duplicate, enhancement

#85 Feature/#84 채점 로직 추가, openAI 질문 방식 미세 조정
  src/apis/openai/openai.service.ts
  src/problems/problems.service.ts
Labels: enhancement

#86 Feature/#79 logout api 추가 구현
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/dtos/logout-response.dto.ts
Labels: enhancement

#87 Feature/#79 logout api 추가 구현
  src/auth/auth.service.ts
Labels: bug

#92 Feature/#91 채점 로직 추가 수정
  src/problems/problems.service.ts
Labels: enhancement

#90 Feature/#89 password 변경 시 validation 추가
  src/users/users.service.ts
Labels: enhancement

#94 Feature/#93 채점 로직 추가 수정, 질문 방식 변경, 모니터링을 위한 console.log 추가
  src/apis/openai/openai.service.ts
  src/problems/problems.service.ts
Labels: bug, enhancement

#95 Feature/#68 CI/CD test
  .dockerignore
  .github/workflows/cicd.yaml
  Dockerfile
  docker-compose.yaml
Labels: wontfix

#97 Feature/#96 password 변경 로직 수정
  src/users/users.service.ts
Labels: bug

#99 Feature/#98 필요 없는 console.log 삭제
  src/users/users.controller.ts
Labels: documentation

#101 Feature/#100 ThrottlerBehindProxyGuard를 사용하도록 수정
  src/app.module.ts
Labels: enhancement

#103 Feature/#102 Trust Proxy 설정
  src/main.ts
Labels: enhancement
